In [2]:
import numpy as np

# Task: Array

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

**Input Format:** A single line of input containing space separated numbers.

**Output Format:** Print the reverse NumPy array with type float.

**Sample Input:** 1 2 3 4 -8 -10

**Sample Output:** [-10.  -8.   4.   3.   2.   1.]

In [3]:
def arrays(arr):
    arr = np.array(arr,dtype=float)
    return np.flip(arr)
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Task: Shape and Reshape

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.


In [4]:
def arrays(arr):
    arr = np.array(arr,dtype=int)
    arr = np.reshape(arr,(3,3))
    print(arr)    

arr = input().strip().split(' ')
arrays(arr)
 

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Task: Transpose

We can generate the transposition of an array using the tool numpy.transpose.
It will not affect the original array, but it will create a new array.

**Input Format**
The first line contains the space separated values of  and .
The next  lines contains the space separated elements of  columns.

**Output Format:** First, print the transpose array and then print the flatten.

**Sample Input**

2 2
1 2
3 4

**Sample Output**

[[1 3]
 [2 4]]
[1 2 3 4]

In [ ]:
import numpy as np

n, m = map(int, input().split())
l = []
for _ in range(n):
    l.append(list(map(int, input().split())))
arr = np.array(l)
print(np.transpose(arr))
print(arr.flatten())