# Day 17 Numpy

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])  #numpy array
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [2]:
arr[1][1]

5

In [3]:
n1 = np.zeros((5,5)) # 5d array with zero values
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
n2 = np.full((5,5),5)
n2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [5]:
n3 = np.arange(5,20)  #array with range 
n3

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**random.randint(low, high=None, size=None, dtype=int)**

In [6]:
n4 = np.random.randint(5,50,size=8)
n4

array([34, 23, 39, 35, 49, 39, 33,  5])

In [7]:
arr.shape # gives row and column 

(2, 4)

In [8]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [9]:
arr.shape = (4,2) #changing row and columns
arr

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [10]:
n5 = np.array([1,2,3,4,5])
n6 = np.array([6,7,8,9,10])
np.vstack((n5,n6)) # create new array by adding verticaly

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.hstack((n5,n6)) # create new array by adding horizontaly

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.column_stack((n5,n6)) # create new array by adding column vise

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [13]:
a1 = np.array(([10, 20, 30, 40, 50]))
a2 = np.array(([10, 40, 60, 80, 90]))
np.intersect1d(a1,a2) # find same values

array([10, 40])

In [14]:
np.setdiff1d(a1,a2) # find diffrent from a1 that not in a2

array([20, 30, 50])

In [15]:
np.setdiff1d(a2,a1) # find diffrent from a2 that not in a1

array([60, 80, 90])

In [16]:
n5 = np.array([1,2,3,4,5])
n6 = np.array([6,7,8,9,10])
np.sum([n5,n6]) # sum of arrays and create new array

55

In [17]:
np.sum([n5,n6], axis=0) # sum with same index values

array([ 7,  9, 11, 13, 15])

In [18]:
np.sum([n5,n6], axis=1) # sum array with its values

array([15, 40])

In [19]:
arr = [10, 20, 30, 40, 50]
arr = np.array(arr)   
sub = arr - 1
sub

array([ 9, 19, 29, 39, 49])

In [20]:
add = arr +2
add

array([12, 22, 32, 42, 52])

In [21]:
multi = arr * 2
multi

array([ 20,  40,  60,  80, 100])

In [22]:
divide = arr/ 2
divide

array([ 5., 10., 15., 20., 25.])

In [23]:
arr = [10, 20, 30, 40, 50]
np.mean(arr)

30.0

In [24]:
np.median(arr)

30.0

In [25]:
np.std(arr)

14.142135623730951

In [26]:
np.save('my_arr',arr)  # saving numpy array in file
larr = np.load('my_arr.npy') # loading array file
larr

array([10, 20, 30, 40, 50])

In [27]:
emp = np.empty((3,5)) #random generated array
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
x =  [[1,2,3,4,5],[6,7,8,9,10],[11, 12, 13, 14, 15]]
ar = np.array(x)
ar.sum(axis=1)

array([15, 40, 65])

In [29]:
ar.T # Transpose

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [30]:
ar.ndim # no of dimensions

2

In [31]:
m = np.array([1,34,32,55,40])
m.argmax() # returns index of maximum value

3

In [32]:
m.argmin() # return index of minmum value

0

In [33]:
ran = np.array([30 ,4,63, 65,68,77,44,22,6,7])
np.where(ran>30) # gives indexces where values grater then 30

(array([2, 3, 4, 5, 6], dtype=int64),)

In [34]:
np.flip(m)

array([40, 55, 32, 34,  1])